In [1]:
import numpy as np           # This package will be useful for numerical operations
import pandas as pd          # This package will help with data handling and manipulation
import os                    # This package will help you navigate the directory structure
import cv2                   # This package will use OpenCV for image processing


# sklearn is a Machine learning toolkit
# By importing the "train_test_split" functionality, We can split your dataset into two subsets for "training" and "testing"
# By importing the "KNeighborsClassifier" functionality, We can perform the implementation of the K-Nearest Neighbors (K-NN) classification algorithm
# The "confusion_matrix" functionality provides a summary table that describes the model's performance by comparing actual and predicted labels.
# The "accuracy_score" functionality helps measure the proportion of correctly classified instances.

from sklearn.model_selection import train_test_split    
from sklearn.neighbors import KNeighborsClassifier      
from sklearn.metrics import confusion_matrix, accuracy_score 

In [2]:
# Here we are defining the data directory and its labels.
dataDIR_DR = 'DR'
categories_Names = ['0.0.Normal', '10.0.Possible glaucoma', '13.Dragged Disc', '27.Laser Spots']

# We are creating two lists to store the "images" and "labels".
img_data = []
img_fd_labels = []

# Using a for loop, we iterate through each category directory, load "images" and "labels," and determine the class label based on the category index
for category in categories_Names: 
    path = os. path.join(dataDIR_DR, category)
    class_num = categories_Names.index(category) 
    
    for img in os.listdir(path):
        
        try:
            img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
            img_array = cv2.resize(img_array, (256, 256))  

            """
            We are resizing the image pixels to standardize their input size, which offers several benefits:
            1. Consistency: Ensures all images have the same dimensions, which is crucial for the K-NN algorithm to effectively compare them.
            2. Efficiency: Smaller images reduce computational load and memory usage. Processing large, high-resolution images can be slow 
            and cumbersome.
            3. Simplicity: It is easier to manage and work with standardized image sizes, especially when training simple models like K-NN.
            
            The "ideal" size often depends on balancing detail with computational efficiency. 
            For medical images like these, a good starting point would be in the range of 64x64 to 256x256 pixels:
            - 64x64 or 128x128: Small enough to be computationally manageable, yet retains decent detail.
            - 100x100 or 150x150: A middle ground, offering more detail but still reasonable processing time.
            - 256x256: High detail, but requires more computational power and memory.

            """
            
            # Here we are storing the image arrays alongside their corresponding labels
            img_data.append(img_array)
            img_fd_labels.append(class_num) 
        except Exception as e:
            pass


In [3]:
# Converting the array into numpy arrays
# Converting the list of images into a flattened array suitable for K-NN
# Converting the label list to a numpy array

img_data = np.array(img_data).reshape(-1, 256*256)
img_fd_labels = np.array(img_fd_labels)

In [4]:
# Dividing the dataset into 80% for training and 20% for testing sets ensures reproducibility with random_state=42

X_train, X_test, y_train, y_test = train_test_split(img_data, img_fd_labels, test_size=0.2, random_state=42)


In [5]:
# Initializing and training the K-NN model
# Setting n_neighbors=3 in K-NN means the algorithm looks at the 3 closest points to decide the class and fit the model using the training data

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [6]:
# Predicting labels for the test data
y_pred = knn.predict(X_test)



In [7]:
# The confusion matrix provides a visual representation of performance by comparing the actual labels of a model with the labels it predicted
# The accuracy score represents the overall accuracy of the model

cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix is :\n", cm)
print("Accuracy of the Model is:", accuracy)

Confusion Matrix is :
 [[10  0  1]
 [ 0  2  0]
 [ 0  0  4]]
Accuracy of the Model is: 0.9411764705882353


In [8]:
"""
--> In his task, we used three labels (Normal, Possible Glaucoma, Dragged Disc, and Laser Spots)
--> Each image was converted to grayscale and resized to 256x256 pixels for more effective results, even though high-resolution images can be slow and cumbersome.
--> This standardization was necessary to ensure consistency across all images for processing by our model.
--> For model training and testing, we chose the K-Nearest Neighbors (K-NN) algorithm, configuring it specifically with three neighbors. 
--> We split the dataset, using 80% for training and the remaining 20% for testing. This split allowed us to assess the model's 
    capability to generalize to new, unseen data.
--> Regarding model performance, we used a confusion matrix to evaluate the classifier. 
--> This matrix provided a clear view of correct and incorrect predictions across different categories, helping us understand how well the model was 
    performing. 
--> Additionally, we calculated the accuracy score, which gave a percentage of correctly classified instances, serving as a quick gauge 
    of overall model performance.

In our observations, we found that the model achieved a reasonable accuracy, indicating that our preprocessing approach and use of K-NN were effective. 
However, the confusion matrix revealed some misclassifications, particularly between categories like Possible Glaucoma and Dragged Disc.

"""

"\n--> In his task, we used three labels (Normal, Possible Glaucoma, Dragged Disc, and Laser Spots)\n--> Each image was converted to grayscale and resized to 256x256 pixels for more effective results, even though high-resolution images can be slow and cumbersome.\n--> This standardization was necessary to ensure consistency across all images for processing by our model.\n--> For model training and testing, we chose the K-Nearest Neighbors (K-NN) algorithm, configuring it specifically with three neighbors. \n--> We split the dataset, using 80% for training and the remaining 20% for testing. This split allowed us to assess the model's \n    capability to generalize to new, unseen data.\n--> Regarding model performance, we used a confusion matrix to evaluate the classifier. \n--> This matrix provided a clear view of correct and incorrect predictions across different categories, helping us understand how well the model was \n    performing. \n--> Additionally, we calculated the accuracy sc